### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by sferencik** [etsy/logster#91]
Unfortunately, logster doesn't work on Windows due to the dependency on `fcntl`. You _do_ intend to support Windows, don't you? (Judging by what I've read about the use of `pygtail`.)

Would it be OK to use `portalocker` instead of `fcntl`? Or use it optionally, e.g. `logster --tailer pygtail --locker portalocker`?

**Comment by sferencik** [comment]
BTW, I have no experience with `portalocker` yet; I'm only suggesting it as it comes up as the suggestion when googling for "python flock on windows".

**Comment by benburry** [comment]
Unfortunately we don't actively support logster on Windows. If the two are functionally equivalent I see no reason not to incorporate portalocker as an alternative to fcntl, but this won't be something we'd be incorporating ourselves.

A PR would be most welcome, of course
