### ISSUE TITLE
Please tag a version number

### ISSUE THREAD

**Issue by sferencik** [etsy/logster#93]
As mentioned in #92, I've asked Enthought to include logster (and pygtail and portalocker) in a Canopy repo. They've agreed to do so but would appreciate if you could tag a version. For obvious reasons they don't want to pick an arbitrary point (would _you_ bless one instead?) and the constant version number of 0.0.1 isn't too convenient for them either.

Thanks,
Sam

**Comment by benburry** [comment]
Tagged 1.0.0

**Comment by benburry** [comment]
Please use version 1.0.1

Version 1.0.0 has compatibility issues with python 2

**Comment by sferencik** [comment]
Sure, thanks.
