### ISSUE TITLE
Metric is different than supposed to be.

### ISSUE THREAD

**Issue by krzysztofzygmunt** [etsy/logster#99]
I've created empty file for test and run logster like this:
`logster --dry-run -o stdout MetricLogster /tmp/diff_log`

Then I've put data into test log file as in example:

METRIC_COUNT metric=some.metric.count value=1
METRIC_COUNT metric=some.metric.count value=2.2

and run logster again and it gave me this output:
`some.metric.count 0.2`

It's written that COUNT metrics are totalled which should give  3.2.

Why it's not working as intended ?

version:
`ii  logster                            0.0.1-1                           all          Generate metrics from logfiles for Graphite and G`

**Comment by benburry** [comment]
The MetricLogster parser calculates values _per-second_, so the values will depend on the time between the two runs in your example

The code that does this is [here](https://github.com/etsy/logster/blob/e961ad90d3801eea0fd52ee89af644b3339ae3f5/logster/parsers/MetricLogster.py#L95-L96)
